// Stub for preferences config.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenPreferencesResourceLoaderConfig.
module.exports = {
	wgCitizenPreferencesConfig: {
		'skin-theme': {
			enabled: true,
			default: 'os',
			options: [ 'os', 'day', 'night' ]
		},
		'citizen-feature-custom-font-size': {
			enabled: true,
			default: 'standard',
			options: [ 'small', 'standard', 'large', 'xlarge' ]
		},
		'citizen-feature-custom-width': {
			enabled: true,
			default: 'standard',
			options: [ 'standard', 'expanded', 'wide', 'full' ]
		},
		'citizen-feature-pure-black': {
			enabled: true,
			default: '0',
			options: [ '0', '1' ]
		},
		'citizen-feature-image-dimming': {
			enabled: true,
			default: '0',
			options: [ '0', '1' ]
		},
		'citizen-feature-autohide-navigation': {
			enabled: true,
			default: '1',
			options: [ '0', '1' ]
		},
		'citizen-feature-performance-mode': {
			enabled: true,
			default: '1',
			options: [ '0', '1' ]
		}
	}
};
